api = "0.7"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/nodejs"
  id = "neeto-deploy/nodejs"
  name = "Paketo Buildpack for Node.js"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/nodejs/blob/main/LICENSE"

[metadata]
  include-files = ["buildpack.toml"]

[[order]]

  [[order.group]]
    id = "neeto-deploy/node-engine"
    version = "6.0.0"

  [[order.group]]
    id = "neeto-deploy/yarn"
    version = "2.0.1"

  [[order.group]]
    id = "neeto-deploy/yarn-install"
    version = "2.1.11"

  [[order.group]]
    id = "neeto-deploy/node-run-script"
    optional = true
    version = "2.1.7"

  [[order.group]]
    id = "neeto-deploy/node-start"
    optional = true
    version = "2.2.7"

  [[order.group]]
    id = "neeto-deploy/yarn-start"
    optional = true
    version = "2.0.25"

[[order]]

  [[order.group]]
    id = "neeto-deploy/node-engine"
    version = "6.0.0"

  [[order.group]]
    id = "neeto-deploy/npm-install"
    version = "1.8.1"

  [[order.group]]
    id = "neeto-deploy/node-run-script"
    optional = true
    version = "2.1.7"

  [[order.group]]
    id = "neeto-deploy/node-start"
    optional = true
    version = "2.2.7"

  [[order.group]]
    id = "neeto-deploy/npm-start"
    optional = true
    version = "2.1.6"

[[order]]


  [[order.group]]
    id = "neeto-deploy/node-engine"
    version = "6.0.0"

  [[order.group]]
    id = "neeto-deploy/node-start"
    version = "2.2.7"

